# cnot_gate
# CNOT gate - entangles two qubits
# Dimensions: (20, 6, 15)
# Block count: 83

setblock ~0 ~4 ~14 minecraft:redstone_wire
setblock ~0 ~4 ~13 minecraft:redstone_wire
setblock ~1 ~4 ~14 minecraft:redstone_wire
setblock ~1 ~4 ~13 minecraft:redstone_wire
setblock ~2 ~4 ~14 minecraft:redstone_wire
setblock ~2 ~4 ~13 minecraft:redstone_wire
setblock ~3 ~4 ~14 minecraft:redstone_wire
setblock ~3 ~4 ~13 minecraft:redstone_wire
setblock ~4 ~4 ~14 minecraft:redstone_wire
setblock ~4 ~4 ~13 minecraft:redstone_wire
setblock ~5 ~4 ~14 minecraft:redstone_wire
setblock ~5 ~4 ~13 minecraft:redstone_wire
setblock ~6 ~4 ~14 minecraft:redstone_wire
setblock ~6 ~4 ~13 minecraft:redstone_wire
setblock ~7 ~4 ~14 minecraft:redstone_wire
setblock ~7 ~4 ~13 minecraft:redstone_wire
setblock ~8 ~4 ~14 minecraft:redstone_wire
setblock ~8 ~4 ~13 minecraft:redstone_wire
setblock ~9 ~4 ~14 minecraft:redstone_wire
setblock ~9 ~4 ~13 minecraft:redstone_wire
setblock ~10 ~4 ~14 minecraft:redstone_wire
setblock ~10 ~4 ~13 minecraft:redstone_wire
setblock ~11 ~4 ~14 minecraft:redstone_wire
setblock ~11 ~4 ~13 minecraft:redstone_wire
setblock ~12 ~4 ~14 minecraft:redstone_wire
setblock ~12 ~4 ~13 minecraft:redstone_wire
setblock ~13 ~4 ~14 minecraft:redstone_wire
setblock ~13 ~4 ~13 minecraft:redstone_wire
setblock ~14 ~4 ~14 minecraft:redstone_wire
setblock ~14 ~4 ~13 minecraft:redstone_wire
setblock ~15 ~4 ~14 minecraft:redstone_wire
setblock ~15 ~4 ~13 minecraft:redstone_wire
setblock ~16 ~4 ~14 minecraft:redstone_wire
setblock ~16 ~4 ~13 minecraft:redstone_wire
setblock ~17 ~4 ~14 minecraft:redstone_wire
setblock ~17 ~4 ~13 minecraft:redstone_wire
setblock ~18 ~4 ~14 minecraft:redstone_wire
setblock ~18 ~4 ~13 minecraft:redstone_wire
setblock ~19 ~4 ~14 minecraft:redstone_wire
setblock ~19 ~4 ~13 minecraft:redstone_wire
setblock ~10 ~4 ~12 minecraft:comparator[facing=south,mode=compare]
setblock ~10 ~4 ~11 minecraft:stone
setblock ~10 ~4 ~10 minecraft:redstone_wire
setblock ~0 ~0 ~7 minecraft:redstone_wire
setblock ~0 ~0 ~0 minecraft:redstone_wire
setblock ~1 ~0 ~7 minecraft:redstone_wire
setblock ~1 ~0 ~0 minecraft:redstone_wire
setblock ~2 ~0 ~7 minecraft:redstone_wire
setblock ~2 ~0 ~0 minecraft:redstone_wire
setblock ~3 ~0 ~7 minecraft:redstone_wire
setblock ~3 ~0 ~0 minecraft:redstone_wire
setblock ~4 ~0 ~7 minecraft:redstone_wire
setblock ~4 ~0 ~0 minecraft:redstone_wire
setblock ~5 ~0 ~7 minecraft:redstone_wire
setblock ~5 ~0 ~0 minecraft:redstone_wire
setblock ~6 ~0 ~7 minecraft:redstone_wire
setblock ~6 ~0 ~0 minecraft:redstone_wire
setblock ~7 ~0 ~7 minecraft:redstone_wire
setblock ~7 ~0 ~0 minecraft:redstone_wire
setblock ~8 ~0 ~7 minecraft:sticky_piston[facing=south]
setblock ~8 ~0 ~0 minecraft:sticky_piston[facing=north]
setblock ~10 ~3 ~10 minecraft:redstone_wire
setblock ~10 ~2 ~10 minecraft:redstone_wire
setblock ~10 ~1 ~10 minecraft:redstone_wire
setblock ~10 ~0 ~10 minecraft:redstone_wire
setblock ~9 ~0 ~10 minecraft:redstone_wire
setblock ~8 ~0 ~10 minecraft:redstone_wire
setblock ~12 ~0 ~7 minecraft:redstone_wire
setblock ~12 ~0 ~0 minecraft:redstone_wire
setblock ~13 ~0 ~7 minecraft:redstone_wire
setblock ~13 ~0 ~0 minecraft:redstone_wire
setblock ~14 ~0 ~7 minecraft:redstone_wire
setblock ~14 ~0 ~0 minecraft:redstone_wire
setblock ~15 ~0 ~7 minecraft:redstone_wire
setblock ~15 ~0 ~0 minecraft:redstone_wire
setblock ~16 ~0 ~7 minecraft:redstone_wire
setblock ~16 ~0 ~0 minecraft:redstone_wire
setblock ~17 ~0 ~7 minecraft:redstone_wire
setblock ~17 ~0 ~0 minecraft:redstone_wire
setblock ~18 ~0 ~7 minecraft:redstone_wire
setblock ~18 ~0 ~0 minecraft:redstone_wire
setblock ~19 ~0 ~7 minecraft:redstone_wire
setblock ~19 ~0 ~0 minecraft:redstone_wire