# phase_evolution_engine
# 16-step phase evolution with cos²/sin² lookup
# Dimensions: (60, 4, 20)
# Block count: 102

setblock ~10 ~0 ~10 minecraft:hopper[facing=east]
setblock ~10 ~0 ~11 minecraft:comparator[facing=south,mode=compare]
setblock ~12 ~0 ~10 minecraft:hopper[facing=east]
setblock ~12 ~0 ~11 minecraft:comparator[facing=south,mode=compare]
setblock ~14 ~0 ~10 minecraft:hopper[facing=east]
setblock ~14 ~0 ~11 minecraft:comparator[facing=south,mode=compare]
setblock ~16 ~0 ~10 minecraft:hopper[facing=east]
setblock ~16 ~0 ~11 minecraft:comparator[facing=south,mode=compare]
setblock ~16 ~0 ~12 minecraft:hopper[facing=east]
setblock ~16 ~0 ~13 minecraft:comparator[facing=south,mode=compare]
setblock ~16 ~0 ~14 minecraft:hopper[facing=east]
setblock ~16 ~0 ~15 minecraft:comparator[facing=south,mode=compare]
setblock ~16 ~0 ~16 minecraft:hopper[facing=east]
setblock ~16 ~0 ~17 minecraft:comparator[facing=south,mode=compare]
setblock ~16 ~0 ~18 minecraft:hopper[facing=east]
setblock ~16 ~0 ~19 minecraft:comparator[facing=south,mode=compare]
setblock ~14 ~0 ~18 minecraft:hopper[facing=east]
setblock ~14 ~0 ~19 minecraft:comparator[facing=south,mode=compare]
setblock ~12 ~0 ~18 minecraft:hopper[facing=east]
setblock ~12 ~0 ~19 minecraft:comparator[facing=south,mode=compare]
setblock ~10 ~0 ~18 minecraft:hopper[facing=east]
setblock ~10 ~0 ~19 minecraft:comparator[facing=south,mode=compare]
setblock ~10 ~0 ~16 minecraft:hopper[facing=east]
setblock ~10 ~0 ~17 minecraft:comparator[facing=south,mode=compare]
setblock ~10 ~0 ~14 minecraft:hopper[facing=east]
setblock ~10 ~0 ~15 minecraft:comparator[facing=south,mode=compare]
setblock ~10 ~0 ~12 minecraft:hopper[facing=east]
setblock ~10 ~0 ~13 minecraft:comparator[facing=south,mode=compare]
setblock ~12 ~0 ~14 minecraft:hopper[facing=east]
setblock ~12 ~0 ~15 minecraft:comparator[facing=south,mode=compare]
setblock ~14 ~0 ~14 minecraft:hopper[facing=east]
setblock ~14 ~0 ~15 minecraft:comparator[facing=south,mode=compare]
setblock ~20 ~0 ~10 minecraft:chest
setblock ~21 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~22 ~0 ~10 minecraft:chest
setblock ~23 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~24 ~0 ~10 minecraft:chest
setblock ~25 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~26 ~0 ~10 minecraft:chest
setblock ~27 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~28 ~0 ~10 minecraft:chest
setblock ~29 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~30 ~0 ~10 minecraft:chest
setblock ~31 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~32 ~0 ~10 minecraft:chest
setblock ~33 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~34 ~0 ~10 minecraft:chest
setblock ~35 ~0 ~10 minecraft:comparator[facing=east,mode=compare]
setblock ~20 ~0 ~14 minecraft:chest
setblock ~21 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~22 ~0 ~14 minecraft:chest
setblock ~23 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~24 ~0 ~14 minecraft:chest
setblock ~25 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~26 ~0 ~14 minecraft:chest
setblock ~27 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~28 ~0 ~14 minecraft:chest
setblock ~29 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~30 ~0 ~14 minecraft:chest
setblock ~31 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~32 ~0 ~14 minecraft:chest
setblock ~33 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~34 ~0 ~14 minecraft:chest
setblock ~35 ~0 ~14 minecraft:comparator[facing=east,mode=compare]
setblock ~36 ~0 ~12 minecraft:redstone_wire
setblock ~37 ~0 ~12 minecraft:redstone_wire
setblock ~38 ~0 ~12 minecraft:redstone_wire
setblock ~39 ~0 ~12 minecraft:redstone_wire
setblock ~36 ~0 ~14 minecraft:redstone_wire
setblock ~37 ~0 ~14 minecraft:redstone_wire
setblock ~38 ~0 ~14 minecraft:redstone_wire
setblock ~39 ~0 ~14 minecraft:redstone_wire
setblock ~40 ~1 ~12 minecraft:redstone_lamp
setblock ~40 ~1 ~14 minecraft:redstone_lamp
setblock ~41 ~1 ~12 minecraft:redstone_lamp
setblock ~41 ~1 ~14 minecraft:redstone_lamp
setblock ~42 ~1 ~12 minecraft:redstone_lamp
setblock ~42 ~1 ~14 minecraft:redstone_lamp
setblock ~43 ~1 ~12 minecraft:redstone_lamp
setblock ~43 ~1 ~14 minecraft:redstone_lamp
setblock ~44 ~1 ~12 minecraft:redstone_lamp
setblock ~44 ~1 ~14 minecraft:redstone_lamp
setblock ~45 ~1 ~12 minecraft:redstone_lamp
setblock ~45 ~1 ~14 minecraft:redstone_lamp
setblock ~46 ~1 ~12 minecraft:redstone_lamp
setblock ~46 ~1 ~14 minecraft:redstone_lamp
setblock ~47 ~1 ~12 minecraft:redstone_lamp
setblock ~47 ~1 ~14 minecraft:redstone_lamp
setblock ~48 ~1 ~12 minecraft:redstone_lamp
setblock ~48 ~1 ~14 minecraft:redstone_lamp
setblock ~49 ~1 ~12 minecraft:redstone_lamp
setblock ~49 ~1 ~14 minecraft:redstone_lamp
setblock ~50 ~1 ~12 minecraft:redstone_lamp
setblock ~50 ~1 ~14 minecraft:redstone_lamp
setblock ~51 ~1 ~12 minecraft:redstone_lamp
setblock ~51 ~1 ~14 minecraft:redstone_lamp
setblock ~52 ~1 ~12 minecraft:redstone_lamp
setblock ~52 ~1 ~14 minecraft:redstone_lamp
setblock ~53 ~1 ~12 minecraft:redstone_lamp
setblock ~53 ~1 ~14 minecraft:redstone_lamp
setblock ~54 ~1 ~12 minecraft:redstone_lamp
setblock ~54 ~1 ~14 minecraft:redstone_lamp